/// Katalog ikon kanji untuk kategori, dompet, target, dll.
class KanjiIcon {
  const KanjiIcon(this.glyph, this.meaning);
  final String glyph;
  final String meaning;
}

const kKanjiIcons = <KanjiIcon>[
  KanjiIcon('食', 'makan'),
  KanjiIcon('茶', 'teh / kopi'),
  KanjiIcon('酒', 'minuman'),
  KanjiIcon('店', 'toko / resto'),
  KanjiIcon('買', 'belanja'),
  KanjiIcon('服', 'pakaian'),
  KanjiIcon('靴', 'sepatu'),
  KanjiIcon('車', 'mobil'),
  KanjiIcon('走', 'perjalanan'),
  KanjiIcon('油', 'bensin'),
  KanjiIcon('駐', 'parkir'),
  KanjiIcon('電', 'listrik'),
  KanjiIcon('雷', 'energi'),
  KanjiIcon('水', 'air'),
  KanjiIcon('網', 'internet'),
  KanjiIcon('話', 'telepon'),
  KanjiIcon('家', 'rumah'),
  KanjiIcon('族', 'keluarga'),
  KanjiIcon('子', 'anak'),
  KanjiIcon('犬', 'hewan'),
  KanjiIcon('医', 'kesehatan'),
  KanjiIcon('薬', 'obat'),
  KanjiIcon('学', 'pendidikan'),
  KanjiIcon('本', 'buku'),
  KanjiIcon('遊', 'hiburan'),
  KanjiIcon('映', 'film'),
  KanjiIcon('音', 'musik'),
  KanjiIcon('旅', 'liburan'),
  KanjiIcon('美', 'kecantikan'),
  KanjiIcon('体', 'olahraga'),
  KanjiIcon('贈', 'hadiah'),
  KanjiIcon('祈', 'ibadah'),
  KanjiIcon('定', 'langganan'),
  KanjiIcon('税', 'pajak'),
  KanjiIcon('返', 'cicilan'),
  KanjiIcon('借', 'utang'),
  KanjiIcon('急', 'darurat'),
  KanjiIcon('給', 'gaji'),
  KanjiIcon('賞', 'bonus'),
  KanjiIcon('業', 'usaha'),
  KanjiIcon('株', 'saham'),
  KanjiIcon('売', 'jual'),
  KanjiIcon('戻', 'kembali'),
  KanjiIcon('金', 'uang'),
  KanjiIcon('銭', 'koin'),
  KanjiIcon('財', 'dompet'),
  KanjiIcon('銀', 'bank'),
  KanjiIcon('札', 'kartu'),
  KanjiIcon('携', 'e-wallet'),
  KanjiIcon('貯', 'tabungan'),
  KanjiIcon('宝', 'harta'),
  KanjiIcon('夢', 'impian'),
  KanjiIcon('星', 'bintang'),
  KanjiIcon('桜', 'sakura'),
  KanjiIcon('山', 'gunung'),
  KanjiIcon('海', 'laut'),
  KanjiIcon('月', 'bulan'),
  KanjiIcon('火', 'api'),
  KanjiIcon('鹿', 'rusa'),
  KanjiIcon('他', 'lainnya'),
];

const kAccountTypes = <String, (String label, String icon)>{
  'cash': ('Tunai', '銭'),
  'bank': ('Bank', '銀'),
  'ewallet': ('E-Wallet', '携'),
  'credit': ('Kartu Kredit', '札'),
  'paylater': ('Paylater', '借'),
  'savings': ('Tabungan', '貯'),
  'investment': ('Investasi', '株'),
  'other': ('Lainnya', '財'),
};

const kPillars = <String, (String label, String kanji, String desc)>{
  'needs': ('Kebutuhan', '生', 'Hal pokok untuk hidup: makan, tempat tinggal, tagihan, transport.'),
  'wants': ('Keinginan', '欲', 'Hal yang menyenangkan tapi tidak wajib: jajan, hiburan, belanja.'),
  'culture': ('Budaya', '文', 'Investasi diri: buku, kursus, olahraga, donasi.'),
  'unexpected': ('Tak Terduga', '急', 'Pengeluaran darurat atau di luar rencana.'),
};
